# Generated by Django 4.2.25 on 2025-10-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('miktar', models.PositiveIntegerField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tedarikci', models.CharField(max_length=200)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
