# Generated by Django 4.1.13 on 2025-11-04 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='tedarikci',
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=100)),
                ('lead_time', models.PositiveIntegerField(help_text='Lead time in days')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('urun', models.ForeignKey(help_text='Ürün bu tedarikçi tarafından teslim edilir', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='urunler.urun')),
            ],
            options={
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
