# Generated by Django 5.2.10 on 2026-01-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_remove_urun_tedarikci_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='miktar',
            field=models.PositiveIntegerField(default=1000, help_text='Amount this supplier can provide'),
            preserve_default=False,
        ),
    ]
